== OpenShift S2I Builder for OASP4J applications

http://www.github.com/oasp/oasp4j

First build the "builder" image

docker build -t s2i-oasp4j .

Then build your app with this builder image

s2i.exe build https://github.com/amarinso/oasp4j-restaurant s2i-oasp4j oasp4j-sample-amarinso


======

This Source-to-Image Builder let's you create projects targetting Java OpenJDK 8 and built with:

* maven
* gradle

NOTE: If a project has a pom.xml and a build.gradle, maven will take precedence

This builder/runtime s2i image can be used with SpringBoot, Vert.X, Wildfly Swarm, DropWizard and many other microservices frameworks. 

== BUILD ENV Options

* *BUILDER_ARGS*: Allows you to specify options to pass to maven or gradle
* *ARTIFACT_APP* : jar/war file generated by the compilation of maven with the bootified OASP4J app

== RUN ENV Options

* *APP_OPTIONS*: Options to pass to *java -jar app.jar ${APP_OPTIONS}*


== Defaults
If you do not specify any BUILDER_ARGS, by default the s2i image will use the following:

* Maven

----
BUILDER_ARGS="package -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga"
----

* Gradle

----
BUILDER_ARGS="build -x test"
----

== Test in OpenShift

* First load all the needed resources in a project.

----
oc create -f https://raw.githubusercontent.com/jorgemoralespou/s2i-java/master/ose3/s2i-java-imagestream.json
----

* Once the builder s2i-java has been registered, you can create an app with:

** Instant app already provided as template
** Using the s2i-java builder image using a regular Git repository

== Samples
There is a lot of example SpringBoot applications https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples[here]


